Views
Andyveloper/blog-app-rails pull request #6
Opened 2022-09-23 23:35 UTC by Andyveloper

# Take into account
- Please don't forget to seed the database as instructed in the README
## Changes and updates
- View will now be rendered properly
- When clicking on 'see all posts' or 'see all comments' it will display the right data
- Methods for most recent inputs are now being applied correctly

2022-09-23 23:49 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 @Andyveloper  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Highlights 💯
✔️ Your git-flow is correct. 
✔️ You set up linter files and no errors. 
✔️ Your pull request is very professional. It has a meaningful title and summary. Keep it up.
___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-09-23 23:49 UTC, ahmetbozaci commented on app/views/users/show.html.erb
> +</div>
- [ ] See all posts button is not appear in the page. Kindly fix it.

![image](https://user-images.githubusercontent.com/38635158/192069981-ce77f084-a242-442b-ac02-980b01235698.png)

2022-09-23 23:49 UTC, ahmetbozaci commented on app/views/posts/_posts.html.erb
> +</div>
- [ ] Kindly add a pagination button on the posts page to follow wireframe.

![image](https://user-images.githubusercontent.com/38635158/192070097-2c3f80c2-e85a-4e2c-8837-c51ade318417.png)

2022-09-23 23:49 UTC, ahmetbozaci commented on db/seeds.rb
> +like10= Like.create(author: second_user, post: post5)
- [ ] Nice to add samples on the seed file. But it is not creating any sample. You can fix it. OPTIONAL
![image](https://user-images.githubusercontent.com/38635158/192070265-42e2e7be-57c0-4409-bf3b-03abe9b32df0.png)

___
### EXAMPLE:
![image](https://user-images.githubusercontent.com/38635158/192070314-2121b864-f18c-4eed-b2c8-82bb11bc37b1.png)

2022-09-24 01:54 UTC, danielufeli approved these changes
Hi @Andyveloper ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Design ✔️

## Optional suggestions
- [Optional] Kindly update your ReadMe 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 08:36 UTC, merged